### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by tyiannak** [theopsall/archeo#1]
The basic steps seem to be working  fine.

Please add the requirements file, this is the list of dependencies i've used btw:
pandas==1.0.5
numpy==1.18.1
matplotlib==3.2.1
opencv_python==4.2.0.34
scipy==1.4.1
pyAudioAnalysis==0.3.5
scikit_learn==0.23.2
tensorflow==2.3.0

**Comment by theopsall** [comment]
Thank you very much for the feedback.
